from pathlib import Path
import json,html
r=Path(__file__).resolve().parents[1]
esc=html.escape
nav='<nav aria-label="main" class="portfolio-nav"><a class="portfolio-name" href="/">mohammad haider <span>/ software engineer</span></a><div><a href="/projects.html">work</a><a href="/notes.html">lab notebooks</a><a href="/resume.html">resumes</a><a href="/contact.html">contact ↗</a></div></nav>'
def page(title,deck,body,eyebrow='lab notebooks'):
 return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} · Mohammad Haider</title><meta name="description" content="{esc(deck)}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/portfolio-pages.css"><link rel="stylesheet" href="/labs/notebook.css"></head><body class="portfolio-page lab-reader">{nav}<header class="lab-hero"><p class="section-eyebrow">{eyebrow}</p><h1>{title}</h1><p class="lab-deck">{deck}</p></header><main>{body}</main><footer class="portfolio-footer"><a href="/">← portfolio home</a><a href="/projects.html">all work</a><a href="https://github.com/haidmoham">github ↗</a></footer></body></html>'
m=json.loads((r/'labs/lmlab/publication.json').read_text())
cards=''
for item in m['notebooks']:
 n=json.loads((r/'labs/lmlab'/item['slug']/'source.ipynb').read_text());outputs=sum(len(c.get('outputs',[])) for c in n['cells'])
 status=f'{outputs} saved output blocks' if outputs else 'source only · no saved cell outputs'
 cards+=f'<article class="lab-card"><p class="section-eyebrow">{item["slug"]}</p><h2>{item["title"]}</h2><p>{item["description"]}</p><p class="lab-status">{status}</p><a href="./{item["slug"]}/">read notebook →</a></article>'
(r/'labs/lmlab/index.html').write_text(page('lmlab','language models, one inspectable mechanism at a time.',f'<section class="lab-path"><h2>a route through the work</h2><p>start with tokenization, then the bigram baseline, then attention. autograd and cuda branch into the mechanisms underneath. each record exposes the original code and retained outputs; incomplete work is labeled as such.</p><a href="./01_tokenizer/">start with tokenization →</a></section><section class="lab-cards" aria-label="notebooks">{cards}</section><section class="lab-path"><h2>publication boundary</h2><p>these are static, commit-pinned exports of selected public notebooks. this site never executes training or notebook cells. source-only records are implementation workspaces, not completed experimental results.</p><a href="https://github.com/haidmoham/lmlab/tree/{m["revision"]}">inspect the source revision ↗</a></section>'))
(r/'labs/robotics/index.html').write_text(page('robotics test bench','question → prediction → experiment → observation → model update.', '''<section class="lab-path robotics-entry"><p class="section-eyebrow">the experiment sequence</p><h2>six preserved experiment records</h2><p>feedback control, coupled dynamics, jacobians, contact, and leg reachability. the original sequence and its source provenance stay intact.</p><a href="/robotics/">open the experiment index →</a></section><section class="lab-cards" aria-label="notebook evidence"><article class="lab-card"><p class="section-eyebrow">retained notebook</p><h2>static support boundary</h2><p>inspect the recorded notebook behind the support-boundary experiment, with code and retained outputs.</p><a href="/notebooks/static-support-boundary.html">read notebook →</a><br><a href="/notebooks/static-support-boundary.ipynb" download>download source ↓</a></article><article class="lab-card"><p class="section-eyebrow">retained notebook</p><h2>leg workspace</h2><p>inspect the recorded leg-reachability study and its geometric workspace.</p><a href="/notebooks/c1n-leg-workspace.html">read notebook →</a><br><a href="/notebooks/c1n-leg-workspace.ipynb" download>download source ↓</a></article></section><section class="lab-path"><h2>from isolated experiments to a robot</h2><p>C-1N is the integration project. its checkpoint explorer preserves earlier standing and walking behavior alongside the accepted STRIDE checkpoint.</p><a href="https://c1n.mhaider.dev/">inspect C-1N ↗</a></section>'''))
(r/'notes.html').write_text(page('lab notebooks','the questions, implementations, and evidence behind the finished work.', '''<section class="lab-cards" aria-label="research spaces"><article class="lab-card"><p class="section-eyebrow">01 / language models</p><h2>lmlab</h2><p>tokenization, a bigram baseline, attention, autograd, and the start of cuda. readable notebook records with expandable source and clearly labeled output coverage.</p><a href="/labs/lmlab/">enter lmlab →</a></article><article class="lab-card robotics-entry"><p class="section-eyebrow">02 / simulation &amp; control</p><h2>robotics test bench</h2><p>controlled MuJoCo experiments with predictions, observations, and model updates. six experiment records and retained computational notebooks.</p><a href="/labs/robotics/">enter the test bench →</a></article></section><section class="lab-path"><h2>reading the process</h2><p>the short record explains the question. the notebook exposes implementation and saved outputs. source links pin the evidence to a revision, and limitations remain visible rather than being polished away.</p><p>these are historical records and works in progress, not fresh runs performed by this website.</p></section><section class="lab-card"><p class="section-eyebrow">other computational work</p><h2>social vulnerability &amp; health</h2><p>a retained analysis notebook. observational relationships do not establish causation.</p><a href="/notebooks/social-impact-phase1.html">read analysis →</a></section>'''))
